query Users {
  users {
    id
    firstName
    lastName
    email
    bio
    location
    image
    cover
    session
    isVerified
    createdAt
    userName
    followers {
      id
      firstName
      lastName
      userName
      email
      refreshToken
      bio
      location
      image
      cover
      session
      isVerified
      createdAt
    }
    following {
      id
    }
  }
}

query User {
  user {
    id
    firstName
    lastName
    userName
    email
    bio
    location
    image
    cover
    isVerified
    createdAt
    followers {
      id
      firstName
      lastName
      userName
      email
      bio
      location
      image
      cover
      session
      isVerified
      createdAt
    }
    following {
      id
      firstName
      lastName
      userName
      email
      bio
      location
      image
      cover
      session
      isVerified
      createdAt
    }
  }
}

query UserById($userId: String) {
  userById(userId: $userId) {
    id
    firstName
    lastName
    userName
    email
    refreshToken
    bio
    location
    image
    cover
    session
    isVerified
    createdAt
    followers {
      id
      firstName
      lastName
      userName
      email
      refreshToken
      bio
      location
      image
      cover
      session
      isVerified
      createdAt
    }
    following {
      id
      firstName
      lastName
      userName
      email
      refreshToken
      bio
      location
      image
      cover
      session
      isVerified
      createdAt
    }
  }
}

mutation Register($input: AuthUserInput) {
  register(input: $input) {
    accessToken
    refreshToken
  }
}

mutation Login($input: AuthUserInput) {
  login(input: $input) {
    accessToken
    refreshToken
  }
}

mutation UpdateUser($input: UserInput) {
  updateUser(input: $input) {
    bio
    cover
    email
    userName
    firstName
    lastName
    image
    isVerified
    location
  }
}

mutation DeleteUser($userId: String) {
  deleteUser(userId: $userId)
}
