query Posts {
  posts {
    author {
      id
      userName
      bio
      firstName
      lastName
      email
      following {
        id
      }
      followers {
        id
      }
      refreshToken
      location
      image
      cover
      session
      isVerified
      createdAt
    }
    comments {
      id
      content
    }
    content
    createdAt
    id
    likes {
      id
      userName
      firstName
      lastName
      image
    }
    media
    sharedPost {
      author {
        firstName
      }
      content
      media
      createdAt
    }
  }
}

query GetPostById($postId: String) {
  getPostById(postId: $postId) {
    id
    content
    media
    sharedPost {
      id
    }
    author {
      id
      firstName
      lastName
      email
      refreshToken
      bio
      location
      image
      cover
      session
      isVerified
      userName
    }
    comments {
      id
      content
      media
      postId
      replies {
        id
        content
        media
        commentId
      }
    }
    likes {
      id
      firstName
      lastName
      email
      bio
      location
      image
      cover
      session
      isVerified
    }
    createdAt
  }
}

mutation AddPost($input: PostInput) {
  addPost(input: $input) {
    id
    content
    media
    sharedPost {
      id
    }
    comments {
      id
      content
      media
      postId
      replies {
        id
        content
        media
        commentId
      }
    }
    likes {
      id
    }
    createdAt
  }
}

mutation UpdatePost($postId: String, $input: PostInput) {
  updatePost(postId: $postId, input: $input) {
    author {
      id
    }
    comments {
      content
      id
      media
    }
    content
    id
    media
    likes {
      id
    }
  }
}

mutation DeletePost($postId: String) {
  deletePost(postId: $postId)
}
